### ISSUE TITLE
Is there any way to specify a custom link widget?

### ISSUE THREAD

**Issue by umarashfaq** [woodenconsulting/react-js-diagrams#7]
I'm able to specify custom node widgets but custom link widgets aren't working. 

On line 388 of DiagramWidget#onMouseDown, we're instantiating `new LinkModel()`. Shouldn't this be coming from one of the instance factories?

**Comment by umarashfaq** [comment]
Fixed it here: https://github.com/emumba-com/react-js-diagrams/commit/034f7282da51bd90814e36ac70f7b32bd55ffdf2

**Comment by umarashfaq** [comment]
@woodenconsulting You could've asked for a PR instead of copy pasting :)

**Comment by woodenconsulting** [comment]
@umarashfaq I went with a slightly different approach, please see [demo5](https://github.com/woodenconsulting/react-js-diagrams/tree/master/demos/demo5). When a link instance factory is registered that will be [used by default](https://github.com/woodenconsulting/react-js-diagrams/commit/3bafc679ee95d5b090af09dbe551f2b27834e360#diff-16a5533ac7d22fe4ce948d73fdd83f58R390) rather than setting via a prop. Please feel free to create PRs for future issues, it's much appreciated!
